# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TourPlanner"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"
session: Storable
session_dir: /tmp
    
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    PLUGIN_BASE: 'Odyssey::TTPlugin'
            
plugins:
  Database:
    dsn: 'dbi:ODBC:OdysseyDB'
    username: jadoo
    password: ip31415
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
      PrintError: 1
      LongReadLen: 102400
  MemcachedFast:
    servers:
      - "127.0.0.1:11211"
    default_timeout: 3600

plack_middlewares:
  -
    - Debug
    - panels
    -
      - Environment
      - Response
      - Timer
      - Memory
      - DBITrace
      - Dancer::Version
      - Dancer::Settings
      - Dancer::Logger
